[package]
name = "libsshkey"
version = "0.1.0"
authors = ["tyan"]
edition = "2018"

[dependencies]
anyhow = "1"
thiserror = "1"
bytes = "1"
base64 = "0.13.0"
hex = "0.4.2"
once_cell = "1.5.2"
bcrypt-pbkdf = "0.4"
rand = "0.7.3"
openssl = "0.10.30"

[dev-dependencies]
rand = "0.7.3"